environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:
    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.12"
      PYTHON_ARCH: "32"
      TOXENV: py27-{base,i18n}

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "32"
      TOXENV: py35-{base,i18n}

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.5"
      PYTHON_ARCH: "32"
      TOXENV: py36-{base,i18n}

  INSTANCENAME: "SQL2008R2SP2"
  PGUSER: postgres
  PGPASSWORD: Password12!

services:
  - postgresql
  - mssql2008r2sp2

install:
  # add postgres to path
  - "SET PATH=C:\\Program Files\\PostgreSQL\\9.4\\bin;%PATH%"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%APPVEYOR_BUILD_FOLDER%;%PATH%"

  - "powershell cp keg_apps/db/user-config-tpl-appveyor.py keg_apps/keg_apps.db-config.py"

  # Check that we have the expected version and architecture for Python
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - pip --version

  # Install tox from the wheelhouse
  - pip install tox wheel codecov pipenv

build: off

before_test:
  - "createdb keg_test"

test_script:
  - pipenv run python -m pip install --upgrade pip
  - pipenv install pymssql
  - pipenv install
  - pipenv run tox

after_test:
  # If tests are successful, create a whl package for the project.
  - python setup.py bdist_wheel
  - ps: "ls dist"

on_success:
  - codecov

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*
