version: 2
jobs:
    build:
        docker:
            - image: level12/python-test-multi
            - image: postgres:13-alpine
              environment:
                  POSTGRES_USER: postgres
                  # Ok for local dev, potentially UNSAFE in other applications.  Don't blindly copy & paste
                  # without considering implications.
                  POSTGRES_HOST_AUTH_METHOD: trust
                  POSTGRES_DB: keg_tests
                  PGPORT: 54321
            - image: mcr.microsoft.com/mssql/server
              environment:
                ACCEPT_EULA: Y
                MSSQL_SA_PASSWORD: "Password12!"
                MSSQL_TCP_PORT: 14331
        steps:
            - checkout

            - run:
                name: folder listing for debugging
                command: ls -al

            - run:
                name: install tox and upgrade pip
                command: pip3.11 install --progress-bar off -U pip tox

            - run:
                name: version checks
                command: |
                    python3.11 --version
                    pip3.11 --version
                    virtualenv --version
                    tox --version

            - run:
                name: run tox
                command: tox

            - store_test_results:
                path: .circleci/test-reports/

            - run:
                name: push code coverage
                command: bash <(curl -s https://codecov.io/bash)
